version: "3.8"

services:
  node:
    container_name: node
    build: .
    ports:
      - "4000:4000"
      - "5555:5555"
    volumes:
      - .:/home/node/src
      # - ./node_modules:/home/reactnative/node_modules
    extra_hosts:
      - "host.docker.internal:172.17.0.1"
